### ISSUE TITLE
Compilation error with ** (EXIT) no process

### ISSUE THREAD

**Issue by syamilmj** [ikeikeikeike/some-sitemap#5]
I'm using Phoenix, getting this error during compilation:

```
== Compilation error on file lib/sitemaps.ex ==
** (exit) exited in: GenServer.call(Sitemap.Config, {:update, #Function<2.23984558/1 in Sitemap.Config.set/2>}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:596: GenServer.call/3
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    lib/sitemaps.ex:10: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I have verified that `:sitemap` is already in my `:applications` list.

Any clues what's missing here? Thanks!

**Comment by TokiTori** [comment]
I've got same error with 0.7.2 and 0.7.3...

**Comment by AnderLuiz** [comment]
+1

**Comment by ikeikeikeike** [comment]
Hmm. `:sitemap` wasn't starting during compilation and because of there is probably not wraping your sitemap's code by function. Could you write this code below into before your sitemap's code? I think that compilation is working well.

```elixir
Application.ensure_all_started :sitemap
```

But this deal is no good due to README.md has given you guys a misunderstanding. I'm sorry that.


If you might use `mix run`, you guys should follow mix task documents, here:
- https://hexdocs.pm/mix/Mix.Tasks.Run.html
- https://hexdocs.pm/mix/Mix.Task.html


If you might use `mix phoenix.server`, `mix release`, etc, you guys should wrap sitemap codd by function, like this

```elixir
defmodule MyApp.Sitemap do
  use Sitemap

  alias MyApp.{Endpoint, Router.Helpers}

  def dosomething do
    create do
      add Helpers.page_path(Endpoint, :index),
        priority: 0.5, changefreq: "hourly", expires: nil
    end

    ping()
  end
end
```

Anyway, I will fix README.md later. Thanks noticed.

**Comment by ikeikeikeike** [comment]
Fixed with https://github.com/ikeikeikeike/sitemap/commit/6998602f349de6617e252b797f24787a0da6f26f https://github.com/ikeikeikeike/sitemap/commit/cd95fe3a39f39ed2844368ad7cb0ad2552c3d62f
